"""Workflow recording & replay (spec section 19).

Every ``bio`` command already appends its argv to ``.bioexplorer/log.json``
(see project.log_command) as it runs. ``replay`` reads that log back and
re-executes the recorded commands in order, in-process, via Click's test
runner -- rebuilding the project deterministically from the same inputs.

Notes/limitations, stated up front rather than discovered the hard way:

- Commands reference files by the path the user originally typed (e.g.
  ``bio import data/seqs.fasta``), so replay must be run from the same
  working directory the original session used.
- ``bio structure view`` launches an interactive GUI viewer -- replaying it
  headlessly doesn't mean much, so it (and ``replay`` itself, to avoid
  accidental recursion) are skipped by default; pass ``--skip ""`` to force
  everything through.
- ``seq_id``s are randomly regenerated by every ``bio import`` (see
  core._new_id), so a command that references one directly by ID (e.g.
  ``bio align --pairwise <id1> <id2>``) would otherwise reference an ID
  that no longer exists once the project is rebuilt from scratch. Replay
  works around this: before resetting, it snapshots the old id->name
  mapping, and while executing rewrites any argv token that was a valid
  old ID into whatever ID the same-named record has been assigned this
  time around. This only helps IDs that survive under an unchanged name
  -- a step that references a record by an ID whose record was renamed
  or never re-created (e.g. --from skips the import that would have
  created it) still fails as before, correctly.
"""

from __future__ import annotations

import re
import shutil
import time
from dataclasses import dataclass, field
from pathlib import Path

from . import project

DEFAULT_SKIP = {"replay"}

# Matches core._new_id()'s format (uuid4().hex[:12]) closely enough to use
# as a cheap pre-filter; membership in the old id->name map (checked by the
# caller) is what actually gates a rewrite, so a coincidental false-positive
# match here is harmless.
_SEQ_ID_TOKEN = re.compile(r"^[0-9a-f]{12}$")


@dataclass
class ReplayStep:
    index: int
    argv: list[str]
    status: str  # "would_execute" | "executed" | "skipped" | "failed"
    error: str | None = None
    ids_rewritten: bool = False


@dataclass
class ReplayReport:
    steps: list[ReplayStep] = field(default_factory=list)
    backup_path: Path | None = None

    @property
    def n_executed(self) -> int:
        return sum(1 for s in self.steps if s.status == "executed")

    @property
    def n_skipped(self) -> int:
        return sum(1 for s in self.steps if s.status == "skipped")

    @property
    def n_failed(self) -> int:
        return sum(1 for s in self.steps if s.status == "failed")


def _backup_and_reset(cwd: Path | None = None) -> Path | None:
    """Snapshot the current .bioexplorer/ before wiping the regenerable
    parts (records/alignments/trees), so a failed replay doesn't destroy
    the only copy of the project. The log itself is left in place -- we
    already have its contents in memory for this replay run."""
    pdir = project.project_dir(cwd)
    if not pdir.exists():
        return None
    backup = pdir.parent / f".bioexplorer_prereplay_{int(time.time())}"
    shutil.copytree(pdir, backup)
    for name in (project.STATE_FILE, project.ALIGNMENTS_DIR, project.TREES_DIR):
        target = pdir / name
        if target.is_dir():
            shutil.rmtree(target)
        elif target.exists():
            target.unlink()
    return backup


def _capture_id_to_name(cwd: Path | None = None) -> dict[str, str]:
    """seq_id -> name for whatever project state exists right now (i.e.
    the *old* IDs, captured before a reset regenerates them)."""
    try:
        return {rec.seq_id: rec.name for rec in project.load_collection(cwd)}
    except FileNotFoundError:
        return {}


def _current_name_to_id(cwd: Path | None = None) -> dict[str, str]:
    """name -> seq_id for the project as it stands *right now* during
    replay (i.e. the *new* IDs assigned so far this run). First-wins on a
    duplicate name, consistent with the by-name lookups used elsewhere."""
    try:
        collection = project.load_collection(cwd)
    except FileNotFoundError:
        return {}
    mapping: dict[str, str] = {}
    for rec in collection:
        mapping.setdefault(rec.name, rec.seq_id)
    return mapping


def _rewrite_ids(argv: list[str], old_id_to_name: dict[str, str], cwd: Path | None = None) -> tuple[list[str], bool]:
    """Replace any argv token that was a valid seq_id in the original run
    with whatever seq_id the same-named record has now. Returns
    (possibly-rewritten argv, whether anything changed)."""
    if not old_id_to_name:
        return argv, False
    name_to_new_id = _current_name_to_id(cwd)
    if not name_to_new_id:
        return argv, False

    rewritten = list(argv)
    changed = False
    for i, token in enumerate(argv):
        if not _SEQ_ID_TOKEN.match(token):
            continue
        name = old_id_to_name.get(token)
        if name is None:
            continue
        new_id = name_to_new_id.get(name)
        if new_id and new_id != token:
            rewritten[i] = new_id
            changed = True
    return rewritten, changed


def replay(
    cwd: Path | None = None,
    skip_commands: set[str] | None = None,
    from_index: int | None = None,
    to_index: int | None = None,
    dry_run: bool = False,
    continue_on_error: bool = False,
    reset_state: bool = True,
) -> ReplayReport:
    """Replay the recorded workflow log.

    ``from_index``/``to_index`` are 1-based, inclusive, matching the step
    numbers this function reports (so a user can re-run ``--from 5 --to 5``
    after fixing whatever failed at step 5).
    """
    entries = project.read_log(cwd)
    if not entries:
        raise FileNotFoundError(
            "no workflow log found (.bioexplorer/log.json) -- nothing to replay"
        )

    skip = set(skip_commands) if skip_commands is not None else set(DEFAULT_SKIP)
    start = (from_index - 1) if from_index else 0
    end = to_index if to_index else len(entries)
    selected = list(enumerate(entries[start:end], start=start + 1))

    report = ReplayReport()

    if dry_run:
        for index, entry in selected:
            argv = entry["argv"]
            top = argv[0] if argv else ""
            status = "skipped" if top in skip else "would_execute"
            report.steps.append(ReplayStep(index=index, argv=argv, status=status))
        return report

    # Capture the *old* id->name mapping before anything is reset -- this
    # is the only point where the original run's IDs are still visible.
    old_id_to_name = _capture_id_to_name(cwd)

    if reset_state:
        report.backup_path = _backup_and_reset(cwd)

    from click.testing import CliRunner

    from .cli import main as cli_main

    # Sub-invocations would otherwise each append their own log entry,
    # making every replay double the log. Suppress logging for the
    # duration of the replay; the fact that a replay happened is evident
    # from the (unmodified) log itself.
    original_log_command = project.log_command
    project.log_command = lambda cwd=None: None
    runner = CliRunner()
    try:
        for index, entry in selected:
            original_argv = entry["argv"]
            top = original_argv[0] if original_argv else ""
            if top in skip:
                report.steps.append(ReplayStep(index=index, argv=original_argv, status="skipped"))
                continue

            argv, ids_rewritten = _rewrite_ids(original_argv, old_id_to_name, cwd)
            result = runner.invoke(cli_main, argv, catch_exceptions=True)
            if result.exit_code != 0:
                error_text = (result.output or str(result.exception) or "").strip()
                report.steps.append(
                    ReplayStep(index=index, argv=argv, status="failed", error=error_text, ids_rewritten=ids_rewritten)
                )
                if not continue_on_error:
                    break
            else:
                report.steps.append(
                    ReplayStep(index=index, argv=argv, status="executed", ids_rewritten=ids_rewritten)
                )
    finally:
        project.log_command = original_log_command

    return report
